### PR TITLE
Rebuild 2.7

### PR DESCRIPTION
**Pull request by bjodah**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Rebuild with new compilers for 2.7

### CODE REVIEW

**Comment by jschueller** [comment]
@bjodah I'm working on unpinning sundials

**Comment by bjodah** [comment]
sounds good. Do we still want a 2.7 version built with the new compilers or is that unnecessary?

**Comment by jschueller** [comment]
Depends if I succeed :)

**Comment by jschueller** [comment]
It's been unpinned in the pinning feedstock.

**Comment by jschueller** [comment]
I can still merge it, but the 1000 release bump is useless without the compiler change, just add +1.

**Comment by mariusvniekerk** [comment]
if you want to do both compilers, go use the conda-forge-config.yaml from master

**Pull request closed without merging**
