### PR TITLE
Bump openblas 0.2.18 -> 0.2.19

### PR DESCRIPTION
**Pull request by bjodah**

### CODE REVIEW

**Comment by bjodah** [comment]
@conda-forge/core should one bump build number when bumping openblas version?

**Comment by ocefpaf** [comment]
> @conda-forge/core should one bump build number when bumping openblas version?

Yes. Otherwise no new package will be uploaded to the channel.

**Comment by bjodah** [comment]
Thanks!

**Comment by bjodah** [comment]
Must have had an old recipe locally, master already used 0.2.19
sorry.

**Pull request closed without merging**
