### PR TITLE
MNT: Re-rendered with conda-smithy 3.1.6 and pinning 2018.07.20

### LINKED ISSUE #22: Inconsistent MD5 sum for sundials-3.1.0 for OS X
I get md5sum mismatch when trying to build a recipe using sundials-3.1.0:

https://travis-ci.org/bjodah/pycvodes/builds/407614803#L316
(from https://github.com/bjodah/pycvodes/pull/82)

To me it looks like there are 2 files corresponding to the same version and hash (!):
https://anaconda.org/conda-forge/sundials/files

Any clue how to get around this? (The files were uploaded at the same time as v3.1.1 was added, @jschueller  do you have any idea what might be the cause of this?)

### PR DESCRIPTION
**Pull request by jschueller**
Manually rerender to fix #22

### CODE REVIEW

**Comment by jschueller** [comment]
@conda-forge/core this feedstock renders differently on the webservice than locally on my linux host.
On the webservice it gives me a job for each python version although this is a lib and does not depend on Python.

**Comment by isuruf** [comment]
Which conda-build version are you using locally?

**Comment by dougalsutherland** [comment]
I get current `master` as `No changes made. This feedstock is up-to-date.` with conda-smithy 3.1.6, pinning 2018.07.20, conda-build 3.10.9, conda 4.5.8 on Linux. Not sure why; maybe to do with the `python  # [win]` requirement under `test`?

**Comment by isuruf** [comment]
Can you remove `python # [win]` under test? https://github.com/conda/conda-build/issues/2989

**Comment by jschueller** [comment]
I guess that was it: #27, thanks

**Pull request closed without merging**
