### PR TITLE
Build static win32 libs

### PR DESCRIPTION
**Pull request by jschueller**
sundials_kinsol.dll doesn't export all of it's symbols when building assimulo package https://github.com/conda-forge/staged-recipes/pull/1727:
```
error LNK2019: unresolved external symbol _KINProcessError referenced in function _KINPinvSetJacFn
```

This switches from shared libs to static on win target (I tried providing both but the import and static libs names clash).

### CODE REVIEW

**Comment by bjodah** [comment]
What do you mean by "import and static libs names clash"? Does the python extension module have the same name as the sundials provided shared library?

**Comment by jschueller** [comment]
The import lib and static lib of sundial.kinsol have the same name: sundial_kinsol.lib.

**Comment by bjodah** [comment]
So it's an upstream problem in the CMake files in sundials really? Any chance of patching those?

**Comment by bjodah** [comment]
Sorry, I'm a bit lost in windows land, but aren't [static libraries](http://stackoverflow.com/questions/913691/dll-and-lib-files-what-and-why) in windows named `.lib` and dynamic ones `.dll`? If so, how could there be a name clash?

**Comment by jschueller** [comment]
- On windows there are static libs (.lib), runtime dynamic libs (.dll) and also linktime import libs (.lib) which are created at the same time as the corresponding dll.

- I would recommend to not even allow to build static AND shared : client packages still have to detect the sundials libs, and only one can have the sundials_xx.lib name : we have to chose.

**Comment by bjodah** [comment]
Thank you for the explanation. I'm fine with using static libraries on windows if that simplifies things.

**Comment by bjodah** [comment]
Pinging @patricksnape who helped me get the recipe building on windows in the first place.

**Comment by bjodah** [comment]
Merging this, thanks @jschueller

**Pull request merged**
