### PR TITLE
Add test using LAPACK, set index type to 32bit integer

### PR DESCRIPTION
**Pull request by bjodah**
I was working on moving from sundials 2.7 to 3.1 when I noticed the lapack headers weren't included in the package on conda-forge. Turns out that even though `-DLAPACK_ENABLE=ON` was passed to cmake, it was disabled by the configure script in sundials (which said that int64_t was not compatible with lapack). So I added `-DSUNDIALS_INDEX_TYPE=int32_t` and added a test which uses lapack.

@jschueller what do you think about these changes? (granted that tests pass)

### CODE REVIEW

**Comment by bjodah** [comment]
@jschueller I had to revert https://github.com/conda-forge/sundials-feedstock/commit/403f847bc00f40e6305ef3128512ec66773576d0 or else there were link errors on CircleCI. You did not add any tests in that commit -- what issues were it supposed to fix?

I believe that adding `gcc` to recipes on conda-forge has generally been advised against (see e.g. https://github.com/conda-forge/numpy-feedstock/issues/15), the `toolchain` package has been used when needed, but here it looks like we can do without?

**Comment by jschueller** [comment]
no need to modify bld.bat ?

**Comment by bjodah** [comment]
I don't think so since openblas is lacking for windows -- so we are currently relying on the (slower) linear algebra functions provided by sundials.

**Comment by bjodah** [comment]
Oh, maybe you meant we should change the index type from 64 to 32 bit on windows (for consistency if nothing else)? Agreed, updating it...

**Comment by jschueller** [comment]
the gcc/libgcc dependency is needed here on linux because sundials links against libomp, which only this package provides.

**Comment by bjodah** [comment]
libgomp I suppose? I see. @conda-forge/core what is the best approach here? I've looked at some lengthy threads about toolchain/upcoming conda build 3 etc. but I haven't managed to understand what the current status is with respect to libgomp. Here is the linking error when we add `gcc`/`libgcc`:
```
/opt/rh/devtoolset-2/root/usr/bin/ld: warning: libgfortran.so.3, needed by /feedstock_root/build_artefacts/sundials_1514663946033/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../lib/libopenblas.so, not found (try using -rpath or -rpath-link)
/feedstock_root/build_artefacts/sundials_1514663946033/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../lib/libopenblas.so: undefined reference to `_gfortran_compare_string@GFORTRAN_1.0'
/feedstock_root/build_artefacts/sundials_1514663946033/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../lib/libopenblas.so: undefined reference to `_gfortran_etime@GFORTRAN_1.0'
/feedstock_root/build_artefacts/sundials_1514663946033/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../lib/libopenblas.so: undefined reference to `_gfortran_pow_i4_i4@GFORTRAN_1.0'
/feedstock_root/build_artefacts/sundials_1514663946033/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../lib/libopenblas.so: undefined reference to `_gfortran_concat_string@GFORTRAN_1.0'
collect2: error: ld returned 1 exit status
```

**Comment by bjodah** [comment]
Setting rpath did the trick. 🎉 
Happy new year!

**Comment by bjodah** [comment]
@jschueller, do you think this is good to merge?

**Pull request merged**
